### ISSUE TITLE
Demo rel 111 don't work

### ISSUE THREAD

**Issue by Kriscd** [arieh/SLBox#1]
Hello arieh
on link
http://arieh.github.com/SLBox/

On fx with console (This is my error)
SLBGalery is not defined
[Interrompi per questo errore] <script type="text/javascript" src="h...raw/master/Source/SLBox.js"></script>

**Comment by arieh** [comment]
the problem is with the github link. I'll fix it

**Comment by arieh** [comment]
fixed (also fix 1.2-1.3 transition bugs)
